# Generated by Django 5.0.6 on 2024-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
