# Generated by Django 5.0.6 on 2024-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
